### ISSUE TITLE
etcd-operator help

### ISSUE THREAD

**Issue by liyin37** [furkanmustafa/yafw4osx#1]
I see you ask question in etcd-opertor,like https://github.com/coreos/etcd-operator/pull/2047 ,how to config  etcd-operator backup use minio storage? please help me

**Comment by furkanmustafa** [comment]
I am sincerely shocked by your method of reaching me for an issue in that repository!

Although I understand that Github provides no meaningful method of further discussion about that..
You should probably use stackexchange/stackoverflow for this kind of thing.

--- 

For an answer to your question. It was apparently more than 2 years ago.. All I could share is that example manifest in that pull request; https://github.com/coreos/etcd-operator/pull/2047#issue-250645682

Please beware, that repository is archived and things might have changed drastically since then.
